### ISSUE TITLE
[Doc]: Improve developer documentation

### ISSUE THREAD

**Issue by Milerius** [trustwallet/wallet-core#2590]
**Motivation**

We aim to improve developer documentation for our different bindings: **wasm**, **kotlin**, **swift**.

**Checklist**

- [x] Document protobuf data structure - Implemented in #2585 
- [x] Kotlin doc codegen #2217 
- [x] Typescript doc codegen #2587 
- [x] Document extra swift data structure  - Implemented in #2592
- [x] Swift doc codegen - Implemented in #2216 

**Research**

See inner issues.
