### ISSUE TITLE
[NewChain]: add Aptos support

### ISSUE THREAD

**Issue by Milerius** [trustwallet/wallet-core#2594]
**Motivation**

[Aptos](https://aptoslabs.com/) is a proposed Layer 1 blockchain that uses the [Move programming language](https://101blockchains.com/move-programming-language-tutorial/)

The goal is to support the blockchain prior to the main net launch.

**Checklist**

- [x] Skeleton, registry.json update - Implemented in #2595 
- [x] Address support - Implemented in #2595 
- [x] Transaction support
    - [x] Transfer support - Implemented in #2595 
    - [x] Token transfer support Implemented in #2595 
    - [x] Script/SmartContract support Implemented in #2595 
    - [x] TransactionPayload support - Implemented in #2595 
    - [x] BCS serialization support - Implemented in #2595 
- [x] NFT - Implemented in #2613 
- [ ] Staking (optional)

**Resources**

[Transfer TypeScript example](https://github.com/aptos-labs/aptos-core/blob/f12c3628d4125e35597b4e6831696a488870b232/ecosystem/typescript/sdk/src/coin_client.ts#L41)
[Transaction Payload](https://github.com/aptos-labs/aptos-core/blob/f12c3628d4125e35597b4e6831696a488870b232/ecosystem/typescript/sdk/src/transaction_builder/builder.ts#L234)
[HRP/ChainID format](https://github.com/aptos-labs/aptos-core/blob/f12c3628d4125e35597b4e6831696a488870b232/ecosystem/typescript/sdk/src/utils/misc.ts#L32)
[Official developer doc](https://aptoslabs.com/developers)
[BCS Clement implementation](https://github.com/doom/wallet-core/tree/bcs)

**Additional context**

There is 3 SDK's: python, rust, typescript

**Comment by hewigovens** [comment]
slip44 id: 637, derivation path used in Martian wallet: `m/44'/637'/0'/0'/0'`

**Comment by Milerius** [comment]
Openning another issue for aptos staking
