### ISSUE TITLE
[Staking]: support transaction for ETH/NEAR/ELROND

### ISSUE THREAD

**Issue by Milerius** [trustwallet/wallet-core#2674]
**Is your feature request related to a problem? Please describe.**

Adding staking transaction to the following blockchains: eth,near,elrond.

**Checklist**

## Ethereum
- [x] Simple smart contract call transaction with existing staking pool like lido
    - [x] C++ Unit test + tx url for the lido staking transaction
    - [x] Swift Unit test
    - [x] Kotlin Unit test
 
## Near

Add tests to mainnet for: https://github.com/trustwallet/wallet-core/blob/55993e9b9418d5af30e1138455076343445e5071/tests/chains/NEAR/TWAnySignerTests.cpp#L40

## Elrond

 - [x] Use generic action - Merged in #2675 
 - [x] C++ unit tests - Merged in #2675 
 - [x] Swift unit tests - Merged in #2675 
 - [x] Kotlin unit tests - Merged in #2675 

**Resources**

[Lido](https://lido.fi/)
[Lido Deployed Smart Contract](https://docs.lido.fi/deployed-contracts/)
[Other eth staking solutions](https://ethereum.org/nl/staking/pools/)
[Staking Rewards Elrond + FAQ](https://www.stakingrewards.com/earn/elrond/)
[Staking Rewards NEAR + FAQ](https://www.stakingrewards.com/earn/near-protocol/)

**Comment by hewigovens** [comment]
Lido / Rocket pool
