### ISSUE TITLE
[Rust] Support Taproot, Ordinals and BRC20

### ISSUE THREAD

**Issue by lamafab** [trustwallet/wallet-core#3178]
_UPDATE_: PR for this is here: https://github.com/trustwallet/wallet-core/pull/3233

## About

In order to implement [BRC20](https://domo-2.gitbook.io/brc-20-experiment/), we need to support the [Ordinal protocol](https://docs.ordinals.com/introduction.html), which requires Taproot. Respectively, wallet-core must be able to create "inscriptions".

[From the docs](https://docs.ordinals.com/inscriptions.html):

> Inscription content is entirely on-chain, stored in taproot script-path spend scripts. Taproot scripts have very few restrictions on their content, and additionally receive the witness discount, making inscription content storage relatively economical.

> Since taproot script spends can only be made from existing taproot outputs, inscriptions are made using a two-phase commit/reveal procedure. First, in the commit transaction, a taproot output committing to a script containing the inscription content is created. Second, in the reveal transaction, the output created by the commit transaction is spent, revealing the inscription content on-chain.

Inscriptions are created with the following Bitcoin script (which never executes):

```
OP_FALSE
OP_IF
  OP_PUSH "ord"
  OP_1
  OP_PUSH "text/plain;charset=utf-8"
  OP_0
  OP_PUSH "Hello, world!"
OP_ENDIF
```

Related:

- https://github.com/trustwallet/wallet-core/discussions/3155
- https://github.com/trustwallet/wallet-core/issues/1785
- https://github.com/trustwallet/wallet-core/issues/3119

### Part 1:

***
_UPDATE 2023-05-26_
I found a Rust project that implements many of Bitcoin mechanisms: https://github.com/rust-bitcoin/rust-bitcoin/
I'm using this to build a MVP as of now and digging through the source code. We can still decide on whether we want to include the full library or strip out the parts that we need.

- [x] Implemented a mechanism to build transactions with custom Scripts (builder pattern).
- [x] Sign transactions with our `tw_keypair` crate.
	- [x] Write unit tests for this, test against bitcoind RPC (_regtest_ mode) output.
- [x] Encode (signed) transaction.
- [x] Implement builder pattern for ordinals.
***

- [x] Implement the construction of Taproot addresses.
- [x] Extend `Script.cpp` with a `buildPayToTaproot` function, which must support two ways of spending the outputs:
	- _2023-05-26_: This will wrap over the Rust code.
	- [x] _key-path_: Spend output with Schnorr signatures and pubkey (the easier way).
		- _2023-05-26_: `rust-bitcoin` handles this for us.
	- [x] _script-path_: Spend output with a Merkle branch (the harder way). Do note that the Ordinal docs explicitly mention this, meaning we need to implement the Merkle tree in order to support Ordinals/BRC20 (I first assumed that we could do this later).
 		- _2023-05-26_: `rust-bitcoin` handles this for us.
- [x] Extend `Script.cpp` with any required `witnessData` construction.
	- _2023-05-26_: This will wrap over the Rust code.
- [x] Implement the construction of the Merkle tree and the extraction of any of its branches.
	- This one might be tricky but I have experience with Merkle trees. Had to deal with the specification of that at my previous role (no this one specifically, though): https://spec.polkadot.network/chap-state#sect-state-storage 
	- _2023-05-26_: `rust-bitcoin` handles this for us.
- [x] ~Extend our [Rust curve implemenation](https://github.com/trustwallet/wallet-core/pull/3169) with Schnorr support (straight forward to do since we rely on [`k256`](https://docs.rs/k256/latest/k256/schnorr/index.html))~
	- _2023-05-26_: `rust-bitcoin` uses the `secp256k1` library underneath, which we got rid-off. I'll try to integrate this with `k256`, if possible. 
	- _2023-06-05_: `tw_keypair` is on hold (audit related), so we'll just stick with `secp256k1` for now which already has support for Schnorr signatures and public key tweaking.
- [x] Add derivation support for Taproot ([BIP86](https://github.com/bitcoin/bips/blob/master/bip-0086.mediawiki))
	- [x] Derivation support for Bitcoin is already implemented and which we can reuse. Taproot address is now generated from the public key.

For the sake of completeness, we should eventually work on this:

- [x] Implement the generation of Segwit addresses.
  - Right now we only support sending to Segwit addresses, but not receiving to a Segwit address.
  - We might get this for free when implementing Taproot, I'll see.

### Part 2:

- [x] Implement construction of Ordinal Inscriptions.
- [x] ~Implement ["Ordinal Theory"](https://docs.ordinals.com/overview.html#rarity) and how it results in the handling of Taproot outputs.~
	- _2023-06-05_: That part is handled by the indexer (network layer). From the wallet-core perspective, we just construct whatever inputs/outputs are provided via FFI.
- [x] (optional) Implement deployment of BRC20 tokens.
- [x] (optional?) Implement the minting of BRC20 tokens.
- [x] Implement the [transfer](https://domo-2.gitbook.io/brc-20-experiment/#transfer-brc-20) of BRC20 tokens.

**Comment by vccomnet** [comment]
Hi lamafab， 
Thank you for your great work. I would like to know when the development can be completed and released?

**Comment by lamafab** [comment]
@vccomnet just opened this last night -> https://github.com/trustwallet/wallet-core/pull/3233, _almost_ there!

**Comment by lamafab** [comment]
It's done

**Comment by weixuefeng** [comment]
Can i generate taproot address with wallet-core now? i uesd @trustwallet/wallet-core.

**Comment by Milerius** [comment]
Hey @weixuefeng no it's not possible, there is the current status:

```
- Support for **BRC20 transfers**, sending and receiving:
    - [x]  Implemented and tested in Wallet Core.
    - [x]  Publicly exposed (high priority).
- Support for P2WPKH (**Segwit**), sending and receiving:
    - [x]  Implemented and tested in Wallet Core.
    - [ ]  Publicly exposed via C interface (low priority).
- Support for P2TR key-path (**Taproot**), sending and receiving:
    - [x]  Implemented and tested in Wallet Core.
    - [ ]  Publicly exposed via C interface (low priority).
```

**Comment by hanxianlong** [comment]
> Hey @weixuefeng no it's not possible, there is the current status:
> 
> * Support for **BRC20 transfers**, sending and receiving:
>   
>   * [x]   Implemented and tested in Wallet Core.
>   * [x]   Publicly exposed (high priority).
> * Support for P2WPKH (**Segwit**), sending and receiving:
>   
>   * [x]   Implemented and tested in Wallet Core.
>   * [x]    Publicly exposed
> * Support for P2TR key-path (**Taproot**), sending and receiving:
>   
>   * [x]   Implemented and tested in Wallet Core.
>   * [ ]   Publicly exposed via C interface (low priority).

Hi Milerius, is it exposed to C interface now? can I generate taproot address in the iOS App or Android App?

**Comment by lamafab** [comment]
Hey @hanxianlong, it's not exposed yet. We're planning this for Q1 2024.
